I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 368, in script
    "Tour par tour avec sélection manuelle + déplacement au clavier."
  File "game/script.rpy", line 278, in execute
    screen combat_screen():
  File "game/script.rpy", line 278, in execute
    screen combat_screen():
  File "game/script.rpy", line 284, in execute
    key "K_RETURN" action Function(validate_move)
  File "game/script.rpy", line 284, in keywords
    key "K_RETURN" action Function(validate_move)
  File "game/script.rpy", line 284, in <module>
    key "K_RETURN" action Function(validate_move)
NameError: name 'validate_move' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 368, in script
    "Tour par tour avec sélection manuelle + déplacement au clavier."
  File "D:\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "D:\renpy-8.3.7-sdk\renpy\ast.py", line 623, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "D:\renpy-8.3.7-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "D:\renpy-8.3.7-sdk\renpy\character.py", line 1471, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "D:\renpy-8.3.7-sdk\renpy\character.py", line 1117, in do_display
    display_say(who,
  File "D:\renpy-8.3.7-sdk\renpy\character.py", line 814, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "D:\renpy-8.3.7-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\renpy-8.3.7-sdk\renpy\display\core.py", line 2218, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\renpy-8.3.7-sdk\renpy\display\core.py", line 2748, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.3.7-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\renpy-8.3.7-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "D:\renpy-8.3.7-sdk\renpy\display\core.py", line 2748, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\renpy-8.3.7-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "D:\renpy-8.3.7-sdk\renpy\display\screen.py", line 700, in update
    self.screen.function(**self.scope)
  File "game/script.rpy", line 278, in execute
    screen combat_screen():
  File "game/script.rpy", line 278, in execute
    screen combat_screen():
  File "game/script.rpy", line 284, in execute
    key "K_RETURN" action Function(validate_move)
  File "game/script.rpy", line 284, in keywords
    key "K_RETURN" action Function(validate_move)
  File "game/script.rpy", line 284, in <module>
    key "K_RETURN" action Function(validate_move)
NameError: name 'validate_move' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Behegon tactics 1.0
Sat Jul 26 21:22:10 2025
