I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 430, in script
    "Tour par tour avec déplacement au clavier, jusqu'à quatre héros et autant d'ennemis.\n" \
Exception: Sayer '"Tour par tour avec déplacement au clavier, jusqu'à quatre héros et autant d'ennemis.\n" \' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 430, in script
    "Tour par tour avec déplacement au clavier, jusqu'à quatre héros et autant d'ennemis.\n" \
  File "D:\renpy-8.3.7-sdk\renpy\ast.py", line 2586, in execute
    Say.execute(self)
  File "D:\renpy-8.3.7-sdk\renpy\ast.py", line 583, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\renpy-8.3.7-sdk\renpy\ast.py", line 472, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer '"Tour par tour avec déplacement au clavier, jusqu'à quatre héros et autant d'ennemis.\n" \' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Behegon tactics 1.0
Mon Jul 28 02:06:53 2025
